name: ReportWrong
main: com.kan_model.bukkit.First.ReportWrong
version: ' alpha 0.0.5'
author: kan_model
commands:
  reportwrong:
    usage: /repotrwrong 获取更多帮助
    description: 获取更多帮助
    permission-message: 你没有权限！
    aliases: [rw,rp]
permissions:
  reportwrong.*:
    default: true
  reportwrong.list:
    default: op
  reportwrong.check:
    default: op
  reportwrong.deal:
    default: op
  reportwrong.reload:
    default: op
# reportwrong.*:
# 给普通玩家的权限，
# reportwrong.list:
#  使用/rw list的权限
# reportwrong.check:
#  使用/rw list的权限
# reportwrong.deal:
#  使用/rw list的权限
# reportwrong.reload:
#  使用/rw reload的权限